In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from scipy.io import loadmat
import cv2

from utils.bbox_utils import complete_iou, get_iou

2024-07-04 20:34:07.413046: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-04 20:34:07.415363: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-04 20:34:07.422894: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-04 20:34:07.437376: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-04 20:34:07.437405: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-04 20:34:07.447329: I tensorflow/core/platform/cpu_feature_guard.cc:

In [2]:
r_bbox = tf.random.uniform(shape=(2, 4), maxval=224)
tgt_box = tf.random.uniform(shape=(2, 4), maxval=224)
print(r_bbox)

tf.Tensor(
[[124.71415   179.6866    125.93887    67.41244  ]
 [ 41.028442    2.3142586 214.44493   105.51061  ]], shape=(2, 4), dtype=float32)


2024-07-04 20:34:08.962605: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-04 20:34:08.963076: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [3]:
get_iou(r_bbox, tgt_box)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0., -0.],
       [ 0.,  0.]], dtype=float32)>

In [4]:
complete_iou(r_bbox, tgt_box)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-3.5510206 , -0.83772665],
       [-3.5510206 , -0.83772665]], dtype=float32)>

In [6]:
a = tf.broadcast_to(tf.range(0, 10)[tf.newaxis, ...], shape=(9, 10))

In [31]:
idx = np.arange(9)[..., np.newaxis]

In [32]:
idx

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [33]:
tf.gather(a, idx, batch_dims=1)

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

In [ ]:
from_cxcyhw_to_xyxy(r_bbox)

In [ ]:
_penalty_of_weight_height(r_bbox)

In [ ]:
smooth_l1_dist(
    bbox=tf.random.uniform(shape=(40, 4), maxval=100),
    tgt_bbox=tf.random.uniform(shape=(8, 4), maxval=100)
)

In [ ]:
fi = loadmat('/media/daniel/DatasetIMDB/imdb.mat')

In [ ]:
fi

In [ ]:
target = '01/nm0000101_rm532776192_1952-7-1_1995.jpg'

for idx in range(400000):
    if fi['imdb'][0][0][2][0][idx][0] == target:
        print(idx)

In [ ]:
location = fi['imdb'][0][0][5][0][4194][0]

In [ ]:
x1, y1, x2, y2 = tf.cast(location, tf.int32)

In [ ]:
img = cv2.imread('/media/daniel/DatasetIMDB/imdb/' + target)

In [ ]:
face_crop = img[y1:y2, 0:x2]

In [ ]:
face_crop

In [ ]:
cv2.imshow('Cropped Face', face_crop)
cv2.waitKey(0)
cv2.destroyAllWindows()